name: Static Build

on:
  push:
    branches:
      -main

jobs:
  build:
    if: github.repository == 'Denis6Chong/ahorasi'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run build script
        run: python ./remote_build.sh

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update statict build
          commit_user_name: Denis Chong [GitHub Actions]
          commit_user_email: jdchong6@gmail.com
          commit_author: denischong <jdchong6@gmail.com>
